import { User } from "./types";

export const users: User[] = [
  {
    rank: 1,
    name: "Alex Johnson",
    solved: 245,
    accuracy: 98.5,
    points: 12500,
    streak: 15,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    badgeColor: "bg-gradient-to-br from-amber-300 to-yellow-500",
    detailedStats: {
      easyProblemsSolved: 125,
      mediumProblemsSolved: 95,
      hardProblemsSolved: 25,
      contestsParticipated: 12,
      averageSpeed: "2m 45s",
      longestStreak: 21,
      favoriteTopic: "Algorithms",
      joinedDate: "Jan 2024",
      bestRank: 1,
    },
  },
  {
    rank: 2,
    name: "Sarah Chen",
    solved: 238,
    accuracy: 97.8,
    points: 11800,
    streak: 12,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    badgeColor: "bg-gradient-to-br from-gray-300 to-gray-400",
    detailedStats: {
      easyProblemsSolved: 120,
      mediumProblemsSolved: 90,
      hardProblemsSolved: 28,
      contestsParticipated: 10,
      averageSpeed: "3m 10s",
      longestStreak: 17,
      favoriteTopic: "Data Structures",
      joinedDate: "Feb 2024",
      bestRank: 1,
    },
  },
  {
    rank: 3,
    name: "Michael Park",
    solved: 230,
    accuracy: 96.2,
    points: 11200,
    streak: 10,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    badgeColor: "bg-gradient-to-br from-amber-600 to-amber-700",
    detailedStats: {
      easyProblemsSolved: 110,
      mediumProblemsSolved: 85,
      hardProblemsSolved: 35,
      contestsParticipated: 9,
      averageSpeed: "3m 30s",
      longestStreak: 16,
      favoriteTopic: "Dynamic Programming",
      joinedDate: "Dec 2023",
      bestRank: 2,
    },
  },
  {
    rank: 4,
    name: "Emma Wilson",
    solved: 225,
    accuracy: 95.8,
    points: 10800,
    streak: 8,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: 105,
      mediumProblemsSolved: 95,
      hardProblemsSolved: 25,
      contestsParticipated: 8,
      averageSpeed: "4m 15s",
      longestStreak: 14,
      favoriteTopic: "Graphs",
      joinedDate: "Mar 2024",
      bestRank: 3,
    },
  },
  {
    rank: 5,
    name: "David Kim",
    solved: 220,
    accuracy: 94.5,
    points: 10500,
    streak: 7,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: 115,
      mediumProblemsSolved: 80,
      hardProblemsSolved: 25,
      contestsParticipated: 7,
      averageSpeed: "3m 55s",
      longestStreak: 12,
      favoriteTopic: "Sorting",
      joinedDate: "Feb 2024",
      bestRank: 4,
    },
  },
  {
    rank: 6,
    name: "Olivia Martinez",
    solved: 215,
    accuracy: 93.8,
    points: 10200,
    streak: 6,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia",
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: 100,
      mediumProblemsSolved: 85,
      hardProblemsSolved: 30,
      contestsParticipated: 6,
      averageSpeed: "3m 40s",
      longestStreak: 10,
      favoriteTopic: "Binary Search",
      joinedDate: "Jan 2024",
      bestRank: 5,
    },
  },
  {
    rank: 7,
    name: "James Wilson",
    solved: 210,
    accuracy: 93.2,
    points: 9800,
    streak: 9,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: 95,
      mediumProblemsSolved: 85,
      hardProblemsSolved: 30,
      contestsParticipated: 8,
      averageSpeed: "4m 20s",
      longestStreak: 11,
      favoriteTopic: "Trees",
      joinedDate: "Mar 2024",
      bestRank: 6,
    },
  },
  {
    rank: 8,
    name: "Sophia Lee",
    solved: 205,
    accuracy: 92.8,
    points: 9500,
    streak: 8,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia",
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: 90,
      mediumProblemsSolved: 85,
      hardProblemsSolved: 30,
      contestsParticipated: 7,
      averageSpeed: "4m 10s",
      longestStreak: 9,
      favoriteTopic: "Graphs",
      joinedDate: "Feb 2024",
      bestRank: 7,
    },
  },
  {
    rank: 9,
    name: "Daniel Brown",
    solved: 200,
    accuracy: 92.5,
    points: 9200,
    streak: 7,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel",
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: 85,
      mediumProblemsSolved: 85,
      hardProblemsSolved: 30,
      contestsParticipated: 6,
      averageSpeed: "4m 30s",
      longestStreak: 8,
      favoriteTopic: "Arrays",
      joinedDate: "Jan 2024",
      bestRank: 8,
    },
  },
  {
    rank: 10,
    name: "Isabella Garcia",
    solved: 195,
    accuracy: 92.0,
    points: 9000,
    streak: 6,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella",
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: 80,
      mediumProblemsSolved: 85,
      hardProblemsSolved: 30,
      contestsParticipated: 5,
      averageSpeed: "4m 40s",
      longestStreak: 7,
      favoriteTopic: "Strings",
      joinedDate: "Mar 2024",
      bestRank: 9,
    },
  },
  // Adding more users from rank 11 to 50
  ...Array.from({ length: 40 }, (_, i) => ({
    rank: i + 11,
    name: `User ${i + 11}`,
    solved: Math.floor(190 - i * 2),
    accuracy: Math.max(85, 92 - i * 0.2),
    points: Math.floor(8800 - i * 50),
    streak: Math.max(3, 6 - Math.floor(i / 5)),
    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=User${i + 11}`,
    badgeColor: "",
    detailedStats: {
      easyProblemsSolved: Math.floor(75 - i),
      mediumProblemsSolved: Math.floor(80 - i),
      hardProblemsSolved: Math.max(15, 30 - i),
      contestsParticipated: Math.max(2, 5 - Math.floor(i / 8)),
      averageSpeed: `${4 + Math.floor(i / 10)}m ${30 + (i % 10) * 5}s`,
      longestStreak: Math.max(5, 7 - Math.floor(i / 6)),
      favoriteTopic: ["Arrays", "Strings", "Trees", "Graphs", "Dynamic Programming"][i % 5],
      joinedDate: ["Jan", "Feb", "Mar", "Apr", "May"][i % 5] + " 2024",
      bestRank: i + 11,
    },
  })),
]; 